# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# https://doc.scrapy.org/en/latest/topics/items.html

import scrapy


class EplTransfersItem(scrapy.Item):

    Season = scrapy.Field() # season year for transfers
    Club = scrapy.Field() #name of soccer club
    Transfer_Expenditure = scrapy.Field() # $ spent by club on buying players during the season
    Transfer_Income = scrapy.Field() # $ generated by club from selling players during the current season
    Net_Spent = scrapy.Field() # income - spent
    League_Spent = scrapy.Field() # total $ spent by all the clubs inthe EPL during the current season
 
